# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/coordinator/coordinator.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&utils/pb/coordinator/coordinator.proto\x12\x0b\x63oordinator\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n\x07Message\x12\x11\n\tisSuccess\x18\x01 \x01(\x08\x32\x8a\x01\n\x12\x43oordinatorService\x12\x39\n\x07Request\x12\x16.google.protobuf.Empty\x1a\x14.coordinator.Message\"\x00\x12\x39\n\x07Release\x12\x16.google.protobuf.Empty\x1a\x14.coordinator.Message\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.coordinator.coordinator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=84
  _globals['_MESSAGE']._serialized_end=112
  _globals['_COORDINATORSERVICE']._serialized_start=115
  _globals['_COORDINATORSERVICE']._serialized_end=253
# @@protoc_insertion_point(module_scope)
