# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from utils.pb.databaseinstance import databaseinstance_pb2 as utils_dot_pb_dot_databaseinstance_dot_databaseinstance__pb2


class DatabaseInstanceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Read = channel.unary_unary(
                '/databaseinstance.DatabaseInstanceService/Read',
                request_serializer=utils_dot_pb_dot_databaseinstance_dot_databaseinstance__pb2.ReadRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_databaseinstance_dot_databaseinstance__pb2.ReadResponse.FromString,
                )
        self.Write = channel.unary_unary(
                '/databaseinstance.DatabaseInstanceService/Write',
                request_serializer=utils_dot_pb_dot_databaseinstance_dot_databaseinstance__pb2.WriteRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_databaseinstance_dot_databaseinstance__pb2.WriteResponse.FromString,
                )


class DatabaseInstanceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseInstanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=utils_dot_pb_dot_databaseinstance_dot_databaseinstance__pb2.ReadRequest.FromString,
                    response_serializer=utils_dot_pb_dot_databaseinstance_dot_databaseinstance__pb2.ReadResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=utils_dot_pb_dot_databaseinstance_dot_databaseinstance__pb2.WriteRequest.FromString,
                    response_serializer=utils_dot_pb_dot_databaseinstance_dot_databaseinstance__pb2.WriteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'databaseinstance.DatabaseInstanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DatabaseInstanceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/databaseinstance.DatabaseInstanceService/Read',
            utils_dot_pb_dot_databaseinstance_dot_databaseinstance__pb2.ReadRequest.SerializeToString,
            utils_dot_pb_dot_databaseinstance_dot_databaseinstance__pb2.ReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/databaseinstance.DatabaseInstanceService/Write',
            utils_dot_pb_dot_databaseinstance_dot_databaseinstance__pb2.WriteRequest.SerializeToString,
            utils_dot_pb_dot_databaseinstance_dot_databaseinstance__pb2.WriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
