# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/databaseinstance/databaseinstance.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0utils/pb/databaseinstance/databaseinstance.proto\x12\x10\x64\x61tabaseinstance\"\x19\n\x0bReadRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\"\n\x0cReadResponse\x12\x12\n\nstockValue\x18\x01 \x01(\x05\"L\n\x0cWriteRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nstockValue\x18\x02 \x01(\x05\x12\r\n\x05hosts\x18\x03 \x03(\t\x12\r\n\x05ports\x18\x04 \x03(\t\"J\n\rWriteResponse\x12\x11\n\tisSuccess\x18\x01 \x01(\x08\x12\x12\n\nfailedhost\x18\x02 \x01(\t\x12\x12\n\nfailedport\x18\x03 \x01(\t2\xaa\x01\n\x17\x44\x61tabaseInstanceService\x12\x45\n\x04Read\x12\x1d.databaseinstance.ReadRequest\x1a\x1e.databaseinstance.ReadResponse\x12H\n\x05Write\x12\x1e.databaseinstance.WriteRequest\x1a\x1f.databaseinstance.WriteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.databaseinstance.databaseinstance_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_READREQUEST']._serialized_start=70
  _globals['_READREQUEST']._serialized_end=95
  _globals['_READRESPONSE']._serialized_start=97
  _globals['_READRESPONSE']._serialized_end=131
  _globals['_WRITEREQUEST']._serialized_start=133
  _globals['_WRITEREQUEST']._serialized_end=209
  _globals['_WRITERESPONSE']._serialized_start=211
  _globals['_WRITERESPONSE']._serialized_end=285
  _globals['_DATABASEINSTANCESERVICE']._serialized_start=288
  _globals['_DATABASEINSTANCESERVICE']._serialized_end=458
# @@protoc_insertion_point(module_scope)
