# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from utils.pb.orderqueue import orderqueue_pb2 as utils_dot_pb_dot_orderqueue_dot_orderqueue__pb2


class OrderQueueServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enqueue = channel.unary_unary(
                '/orderqueue.OrderQueueService/Enqueue',
                request_serializer=utils_dot_pb_dot_orderqueue_dot_orderqueue__pb2.Order.SerializeToString,
                response_deserializer=utils_dot_pb_dot_orderqueue_dot_orderqueue__pb2.Confirmation.FromString,
                )
        self.Dequeue = channel.unary_unary(
                '/orderqueue.OrderQueueService/Dequeue',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=utils_dot_pb_dot_orderqueue_dot_orderqueue__pb2.Order.FromString,
                )


class OrderQueueServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Enqueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dequeue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderQueueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enqueue': grpc.unary_unary_rpc_method_handler(
                    servicer.Enqueue,
                    request_deserializer=utils_dot_pb_dot_orderqueue_dot_orderqueue__pb2.Order.FromString,
                    response_serializer=utils_dot_pb_dot_orderqueue_dot_orderqueue__pb2.Confirmation.SerializeToString,
            ),
            'Dequeue': grpc.unary_unary_rpc_method_handler(
                    servicer.Dequeue,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=utils_dot_pb_dot_orderqueue_dot_orderqueue__pb2.Order.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orderqueue.OrderQueueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderQueueService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Enqueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderqueue.OrderQueueService/Enqueue',
            utils_dot_pb_dot_orderqueue_dot_orderqueue__pb2.Order.SerializeToString,
            utils_dot_pb_dot_orderqueue_dot_orderqueue__pb2.Confirmation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Dequeue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderqueue.OrderQueueService/Dequeue',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            utils_dot_pb_dot_orderqueue_dot_orderqueue__pb2.Order.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
