# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection/fraud_detection.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_pb2 as common_dot_common__pb2
from suggestions import suggestions_pb2 as suggestions_dot_suggestions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%fraud_detection/fraud_detection.proto\x12\x0f\x66raud_detection\x1a\x13\x63ommon/common.proto\x1a\x1dsuggestions/suggestions.proto\"\x91\x01\n\x15InitializationRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x18\n\x10\x63reditCardNumber\x18\x02 \x01(\t\x12 \n\x18\x63reditCardExpirationDate\x18\x03 \x01(\t\x12\x15\n\rcreditCardCVV\x18\x04 \x01(\t\x12\x14\n\x0c\x64iscountCode\x18\x05 \x01(\t2\xae\x01\n\x15\x46raudDetectionService\x12O\n\x0fInitializeOrder\x12&.fraud_detection.InitializationRequest\x1a\x14.common.ResponseData\x12\x44\n\x0b\x44\x65tectFraud\x12\x13.common.RequestData\x1a .suggestions.SuggestionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection.fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INITIALIZATIONREQUEST']._serialized_start=111
  _globals['_INITIALIZATIONREQUEST']._serialized_end=256
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=259
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=433
# @@protoc_insertion_point(module_scope)
