# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x0f\x66raud_detection\"\x80\x01\n\x15\x46raudDetectionRequest\x12\x18\n\x10\x63reditCardNumber\x18\x01 \x01(\t\x12 \n\x18\x63reditCardExpirationDate\x18\x02 \x01(\t\x12\x15\n\rcreditCardCVV\x18\x03 \x01(\t\x12\x14\n\x0c\x64iscountCode\x18\x04 \x01(\t\"K\n\x16\x46raudDetectionResponse\x12\x0f\n\x07isFraud\x18\x01 \x01(\x08\x12\x14\n\x07message\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message2w\n\x15\x46raudDetectionService\x12^\n\x0b\x44\x65tectFraud\x12&.fraud_detection.FraudDetectionRequest\x1a\'.fraud_detection.FraudDetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRAUDDETECTIONREQUEST']._serialized_start=43
  _globals['_FRAUDDETECTIONREQUEST']._serialized_end=171
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_start=173
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_end=248
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=250
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=369
# @@protoc_insertion_point(module_scope)
