# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from common import common_pb2 as common_dot_common__pb2
from fraud_detection import fraud_detection_pb2 as fraud__detection_dot_fraud__detection__pb2
from suggestions import suggestions_pb2 as suggestions_dot_suggestions__pb2


class FraudDetectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeOrder = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/InitializeOrder',
                request_serializer=fraud__detection_dot_fraud__detection__pb2.InitializationRequest.SerializeToString,
                response_deserializer=common_dot_common__pb2.ResponseData.FromString,
                )
        self.DetectFraud = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/DetectFraud',
                request_serializer=common_dot_common__pb2.RequestData.SerializeToString,
                response_deserializer=suggestions_dot_suggestions__pb2.SuggestionsResponse.FromString,
                )


class FraudDetectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitializeOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FraudDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeOrder,
                    request_deserializer=fraud__detection_dot_fraud__detection__pb2.InitializationRequest.FromString,
                    response_serializer=common_dot_common__pb2.ResponseData.SerializeToString,
            ),
            'DetectFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectFraud,
                    request_deserializer=common_dot_common__pb2.RequestData.FromString,
                    response_serializer=suggestions_dot_suggestions__pb2.SuggestionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fraud_detection.FraudDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FraudDetectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitializeOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud_detection.FraudDetectionService/InitializeOrder',
            fraud__detection_dot_fraud__detection__pb2.InitializationRequest.SerializeToString,
            common_dot_common__pb2.ResponseData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DetectFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud_detection.FraudDetectionService/DetectFraud',
            common_dot_common__pb2.RequestData.SerializeToString,
            suggestions_dot_suggestions__pb2.SuggestionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
