# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\x12\x08\x64\x61tabase\"\x19\n\x0bReadRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\"\n\x0cReadResponse\x12\x12\n\nstockValue\x18\x01 \x01(\x05\"\"\n\x0fPrepareResponse\x12\x0f\n\x07isReady\x18\x01 \x01(\x08\"\x1b\n\rCommitRequest\x12\n\n\x02id\x18\x01 \x01(\t\"#\n\x0e\x43ommitResponse\x12\x11\n\tisSuccess\x18\x01 \x01(\x08\"5\n\x13PrepareWriteRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nstockValue\x18\x02 \x01(\x05\"=\n\x1cPrepareDecrementStockRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tdecrement\x18\x02 \x01(\x05\x32\xfb\x02\n\x0f\x44\x61tabaseService\x12\x35\n\x04Read\x12\x15.database.ReadRequest\x1a\x16.database.ReadResponse\x12H\n\x0cPrepareWrite\x12\x1d.database.PrepareWriteRequest\x1a\x19.database.PrepareResponse\x12@\n\x0b\x43ommitWrite\x12\x17.database.CommitRequest\x1a\x18.database.CommitResponse\x12Z\n\x15PrepareDecrementStock\x12&.database.PrepareDecrementStockRequest\x1a\x19.database.PrepareResponse\x12I\n\x14\x43ommitDecrementStock\x12\x17.database.CommitRequest\x1a\x18.database.CommitResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_READREQUEST']._serialized_start=28
  _globals['_READREQUEST']._serialized_end=53
  _globals['_READRESPONSE']._serialized_start=55
  _globals['_READRESPONSE']._serialized_end=89
  _globals['_PREPARERESPONSE']._serialized_start=91
  _globals['_PREPARERESPONSE']._serialized_end=125
  _globals['_COMMITREQUEST']._serialized_start=127
  _globals['_COMMITREQUEST']._serialized_end=154
  _globals['_COMMITRESPONSE']._serialized_start=156
  _globals['_COMMITRESPONSE']._serialized_end=191
  _globals['_PREPAREWRITEREQUEST']._serialized_start=193
  _globals['_PREPAREWRITEREQUEST']._serialized_end=246
  _globals['_PREPAREDECREMENTSTOCKREQUEST']._serialized_start=248
  _globals['_PREPAREDECREMENTSTOCKREQUEST']._serialized_end=309
  _globals['_DATABASESERVICE']._serialized_start=312
  _globals['_DATABASESERVICE']._serialized_end=691
# @@protoc_insertion_point(module_scope)
