# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\"3\n\x0bRequestData\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x13\n\x0bvectorClock\x18\x02 \x03(\x05\"C\n\x0cResponseData\x12\x11\n\tisSuccess\x18\x01 \x01(\x08\x12\x14\n\x07message\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message\"\x8f\x01\n\x13SuggestionsResponse\x12\x38\n\x05items\x18\x01 \x03(\x0b\x32).common.SuggestionsResponse.SuggestedItem\x1a>\n\rSuggestedItem\x12\x0e\n\x06\x62ookId\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTDATA']._serialized_start=24
  _globals['_REQUESTDATA']._serialized_end=75
  _globals['_RESPONSEDATA']._serialized_start=77
  _globals['_RESPONSEDATA']._serialized_end=144
  _globals['_SUGGESTIONSRESPONSE']._serialized_start=147
  _globals['_SUGGESTIONSRESPONSE']._serialized_end=290
  _globals['_SUGGESTIONSRESPONSE_SUGGESTEDITEM']._serialized_start=228
  _globals['_SUGGESTIONSRESPONSE_SUGGESTEDITEM']._serialized_end=290
# @@protoc_insertion_point(module_scope)
