# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from common import common_pb2 as common_dot_common__pb2
from suggestions import suggestions_pb2 as suggestions_dot_suggestions__pb2
from transaction_verification import transaction_verification_pb2 as transaction__verification_dot_transaction__verification__pb2


class TransactionVerificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeOrder = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/InitializeOrder',
                request_serializer=transaction__verification_dot_transaction__verification__pb2.InitializationRequest.SerializeToString,
                response_deserializer=common_dot_common__pb2.ResponseData.FromString,
                )
        self.VerifyCreditCardNumber = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/VerifyCreditCardNumber',
                request_serializer=common_dot_common__pb2.RequestData.SerializeToString,
                response_deserializer=suggestions_dot_suggestions__pb2.SuggestionsResponse.FromString,
                )
        self.VerifyCreditCardExpiryDate = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/VerifyCreditCardExpiryDate',
                request_serializer=common_dot_common__pb2.RequestData.SerializeToString,
                response_deserializer=suggestions_dot_suggestions__pb2.SuggestionsResponse.FromString,
                )
        self.VerifyOrderItems = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/VerifyOrderItems',
                request_serializer=common_dot_common__pb2.RequestData.SerializeToString,
                response_deserializer=suggestions_dot_suggestions__pb2.SuggestionsResponse.FromString,
                )


class TransactionVerificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitializeOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyCreditCardNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyCreditCardExpiryDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyOrderItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionVerificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeOrder,
                    request_deserializer=transaction__verification_dot_transaction__verification__pb2.InitializationRequest.FromString,
                    response_serializer=common_dot_common__pb2.ResponseData.SerializeToString,
            ),
            'VerifyCreditCardNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyCreditCardNumber,
                    request_deserializer=common_dot_common__pb2.RequestData.FromString,
                    response_serializer=suggestions_dot_suggestions__pb2.SuggestionsResponse.SerializeToString,
            ),
            'VerifyCreditCardExpiryDate': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyCreditCardExpiryDate,
                    request_deserializer=common_dot_common__pb2.RequestData.FromString,
                    response_serializer=suggestions_dot_suggestions__pb2.SuggestionsResponse.SerializeToString,
            ),
            'VerifyOrderItems': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyOrderItems,
                    request_deserializer=common_dot_common__pb2.RequestData.FromString,
                    response_serializer=suggestions_dot_suggestions__pb2.SuggestionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transaction_verification.TransactionVerificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransactionVerificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitializeOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerificationService/InitializeOrder',
            transaction__verification_dot_transaction__verification__pb2.InitializationRequest.SerializeToString,
            common_dot_common__pb2.ResponseData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyCreditCardNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerificationService/VerifyCreditCardNumber',
            common_dot_common__pb2.RequestData.SerializeToString,
            suggestions_dot_suggestions__pb2.SuggestionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyCreditCardExpiryDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerificationService/VerifyCreditCardExpiryDate',
            common_dot_common__pb2.RequestData.SerializeToString,
            suggestions_dot_suggestions__pb2.SuggestionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyOrderItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerificationService/VerifyOrderItems',
            common_dot_common__pb2.RequestData.SerializeToString,
            suggestions_dot_suggestions__pb2.SuggestionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
