# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_verification/transaction_verification.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_pb2 as common_dot_common__pb2
from suggestions import suggestions_pb2 as suggestions_dot_suggestions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7transaction_verification/transaction_verification.proto\x12\x18transaction_verification\x1a\x13\x63ommon/common.proto\x1a\x1dsuggestions/suggestions.proto\"\xa3\x02\n\x15InitializationRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x38\n\x05items\x18\x02 \x03(\x0b\x32).transaction_verification.TransactionItem\x12\x10\n\x08userName\x18\x03 \x01(\t\x12\x13\n\x0buserContact\x18\x04 \x01(\t\x12\x14\n\x0c\x64iscountCode\x18\x05 \x01(\t\x12\x44\n\x0e\x62illingAddress\x18\x06 \x01(\x0b\x32,.transaction_verification.BillingAddressInfo\x12<\n\ncreditCard\x18\x07 \x01(\x0b\x32(.transaction_verification.CreditCardInfo\"1\n\x0fTransactionItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"_\n\x12\x42illingAddressInfo\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\"E\n\x0e\x43reditCardInfo\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t2\xeb\x02\n\x1eTransactionVerificationService\x12X\n\x0fInitializeOrder\x12/.transaction_verification.InitializationRequest\x1a\x14.common.ResponseData\x12O\n\x16VerifyCreditCardNumber\x12\x13.common.RequestData\x1a .suggestions.SuggestionsResponse\x12S\n\x1aVerifyCreditCardExpiryDate\x12\x13.common.RequestData\x1a .suggestions.SuggestionsResponse\x12I\n\x10VerifyOrderItems\x12\x13.common.RequestData\x1a .suggestions.SuggestionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification.transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INITIALIZATIONREQUEST']._serialized_start=138
  _globals['_INITIALIZATIONREQUEST']._serialized_end=429
  _globals['_TRANSACTIONITEM']._serialized_start=431
  _globals['_TRANSACTIONITEM']._serialized_end=480
  _globals['_BILLINGADDRESSINFO']._serialized_start=482
  _globals['_BILLINGADDRESSINFO']._serialized_end=577
  _globals['_CREDITCARDINFO']._serialized_start=579
  _globals['_CREDITCARDINFO']._serialized_end=648
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_start=651
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_end=1014
# @@protoc_insertion_point(module_scope)
