# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_verification.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x18transaction_verification\"\x90\x02\n\x13VerificationRequest\x12\x38\n\x05items\x18\x01 \x03(\x0b\x32).transaction_verification.TransactionItem\x12\x10\n\x08userName\x18\x02 \x01(\t\x12\x13\n\x0buserContact\x18\x03 \x01(\t\x12\x14\n\x0c\x64iscountCode\x18\x04 \x01(\t\x12\x44\n\x0e\x62illingAddress\x18\x05 \x01(\x0b\x32,.transaction_verification.BillingAddressInfo\x12<\n\ncreditCard\x18\x06 \x01(\x0b\x32(.transaction_verification.CreditCardInfo\"1\n\x0fTransactionItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"_\n\x12\x42illingAddressInfo\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\"E\n\x0e\x43reditCardInfo\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"I\n\x14VerificationResponse\x12\x0f\n\x07isValid\x18\x01 \x01(\x08\x12\x14\n\x07message\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message2\x94\x01\n\x1eTransactionVerificationService\x12r\n\x11VerifyTransaction\x12-.transaction_verification.VerificationRequest\x1a..transaction_verification.VerificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VERIFICATIONREQUEST']._serialized_start=61
  _globals['_VERIFICATIONREQUEST']._serialized_end=333
  _globals['_TRANSACTIONITEM']._serialized_start=335
  _globals['_TRANSACTIONITEM']._serialized_end=384
  _globals['_BILLINGADDRESSINFO']._serialized_start=386
  _globals['_BILLINGADDRESSINFO']._serialized_end=481
  _globals['_CREDITCARDINFO']._serialized_start=483
  _globals['_CREDITCARDINFO']._serialized_end=552
  _globals['_VERIFICATIONRESPONSE']._serialized_start=554
  _globals['_VERIFICATIONRESPONSE']._serialized_end=627
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_start=630
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_end=778
# @@protoc_insertion_point(module_scope)
